### ISSUE TITLE
MacOS: make Monu center / align under toolbar icon

### ISSUE THREAD

**Issue by bnvk** [maxogden/monu#15]
Currently, the toolbar UI is horizontally aligning itself a ways away from where the Monu icon is. This is a tad bit jarring UI wise... see pic:

![screen shot 2015-03-24 at 3 21 50 pm](https://cloud.githubusercontent.com/assets/48677/6803685/9d14a688-d239-11e4-9f36-7216f31eb3f8.png)

I'm not sure if Atom-Shell allows for centering it near the toolbar icon, or somehow that is impossible to figure out given current API. 

I'll try to research this a little bit

**Comment by sindresorhus** [comment]
See https://github.com/atom/electron/issues/1500

**Comment by marcbachmann** [comment]
That was implemented in https://github.com/maxogden/menubar/commit/974ba00fc08300853227629dea0414cd75f7f600
